version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: django-drf-template
    container_name: django-drf-template-web
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - django-network

  db:
    image: postgres:14-alpine
    container_name: django-drf-template-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    networks:
      - django-network

  redis:
    image: redis:7-alpine
    container_name: django-drf-template-redis
    networks:
      - django-network

  nginx:
    image: nginx:1.23-alpine
    container_name: django-drf-template-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/certs:/etc/nginx/certs
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - web
    networks:
      - django-network

networks:
  django-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
